### ISSUE TITLE
Reshape error when evaluating

### ISSUE THREAD

**Issue by orbennatan** [ProjectAGI/sparse-unsupervised-capsules#3]
I have tried the command line to evaluate as instructed in the readme: 
!python3 experiment.py --data_dir="/content/drive/My Drive/Colab Notebooks/MNISTForColab" --train=False --checkpoint="/content/drive/My Drive/Colab Notebooks/MNISTForColab/summary_190106/190106-1413/train/model.ckpt-30000" --summary_dir="/content/drive/My Drive/Colab Notebooks/MNISTForColab" --eval_set=test --eval_size=80000 --eval_shard=0

And received the following error. 

tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1600 values, but the requested shape has 784
	 [[{{node input/Reshape}} = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](input/DecodeRaw/_59, input/Reshape/shape)]]
	 [[{{node input/mul/_61}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_22_input/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I started investigating it in the vscode and found it happen in experiment.py inside method eval_experiment line 396 the call to session.run. Obviously it is something that happens inside the graph.

**Comment by orbennatan** [comment]
This is now resolved.
The problem is that you have to make sure you give experiment.py --parameter in a consistent manner. That is, if you use --pad=6 when you build the train file you need to use --pad=6 for the test file. if you use pad=6 the image size 40 by 40. If you use pad=0 the image size is 28X28.

**Comment by abdel** [comment]
Sorry for the late response, glad you got it resolved. I just [updated](https://github.com/ProjectAGI/sparse-unsupervised-capsules/commit/5b98fbb84408d566ae4ef0878008931a65832386) to make this clearer in the affNIST example.
